# Generated by Django 5.1.4 on 2024-12-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
